baseURL = "https://aparker.io/"
languageCode = "en-us"
title = "aparker.io"
theme = "reach"
googleAnalytics = "UA-93794265-1"
enableRobotsTXT = true
canonifyURLs = true

[params]
description = "@austinlparker's blog where i talk about software, the cloud, and other topics"

[permalinks]
post = "/posts/:title/"

[[menu.main]]
name = "posts"
weight = 1
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "about"
weight = 2
identifier = "about"
url = "/about/"